#if os(macOS)
import QuickLookThumbnailing
import SwiftUI

/// First-page PDF preview rendered through `QLThumbnailGenerator`.
///
/// `QLThumbnailGenerator` dispatches to Apple's sandboxed Quick Look
/// XPC service (`com.apple.quicklook.QuickLookSatellite`); the PDF
/// parser, image decoders, and any embedded resources run out of tfx's
/// process and only the rendered NSImage comes back. This trades
/// multi-page scrolling, text selection, and link navigation — which
/// the file preview pane does not need — for a much smaller attack
/// surface:
///
/// - Embedded JavaScript and AcroForms never run (no interactive view).
/// - PDF link actions and external file references are never followed.
/// - Parser exploits land in Apple's sandboxed satellite, not in tfx.
/// - Resource attacks (huge page count, deep object nesting) cap at
///   the satellite's own limits and a single first-page render.
///
/// `.task(id: url)` reruns the load when the previewed file changes,
/// and Swift's task cancellation discards stale results so a rapid
/// pane switch doesn't stamp the wrong image.
struct PDFPreview: View {
    let url: URL

    @State private var image: NSImage?
    @State private var didFinishLoading = false

    var body: some View {
        Group {
            if let image {
                Image(nsImage: image)
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .center)
            } else if didFinishLoading {
                // The satellite returned no representation (corrupt PDF,
                // missing pages, encrypted, file still cloud-only, …).
                // Show a neutral SF Symbol so users can still tell that
                // a preview was attempted here.
                Image(systemName: "doc.richtext")
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .frame(maxWidth: 64, maxHeight: 64)
                    .foregroundStyle(.secondary)
                    .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .center)
            } else {
                ProgressView()
                    .controlSize(.small)
                    .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .center)
            }
        }
        .task(id: url) {
            await load()
        }
    }

    private func load() async {
        // Reset state for the new URL — without this, switching files
        // would briefly show the previous PDF while the new thumbnail
        // is being generated by Quick Look.
        image = nil
        didFinishLoading = false

        let scale = NSScreen.main?.backingScaleFactor ?? 2.0
        // Target size is generous so the result reads well on Retina
        // even when the preview pane is half the window wide; the
        // satellite preserves the document's aspect ratio.
        let size = NSSize(width: 1024, height: 1320)
        let request = QLThumbnailGenerator.Request(
            fileAt: url,
            size: size,
            scale: scale,
            representationTypes: .thumbnail
        )

        let representation = try? await QLThumbnailGenerator.shared
            .generateBestRepresentation(for: request)

        guard !Task.isCancelled else { return }

        image = representation?.nsImage
        didFinishLoading = true
    }
}

#endif
